name: Build plugin (Windows)
on: 
  workflow_call:
    inputs:
      release_tag:
        type: string
        required: true
      release_candidate:
        type: boolean
        required: true
      debug_enabled:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g. 2.1.0-rc.1)'     
        required: true
      release_candidate:
        description: 'Is a release candidate' 
        type: boolean
        required: true
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false

jobs:  
  build:
    name: Building the project
    runs-on: windows-2019
    steps:        
    - name: Git Checkout
      uses: actions/checkout@v2
                  
    - name: Configure
      shell: powershell
      run: |
        .\configure-windows.ps1
                
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      
    - name: CMake
      shell: powershell
      run: |
        cmake . -G "Visual Studio 16 2019" -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_TOOLCHAIN_FILE=D:/a/formula/formula/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_WIN_DIR=D:/a/formula/formula/vcpkg/installed/x64-windows-static -DFORMULA_STANDALONE=1 -DCMAKE_BUILD_TYPE=Release
    
    - name: CMake Build
      shell: powershell
      run: |
        cmake --build . --target Formula_All --config Release
        
    - name: Package
      shell: powershell
      env:
        TAG_NAME: '${{ inputs.release_tag }}'
      run: |
        choco install innosetup -y
        cp Formula_artefacts/Release/Standalone/Formula.exe packaging/windows/
        cp Formula_artefacts/Release/VST3/Formula.vst3/Contents/x86_64-win/Formula.vst3 packaging/windows/
        cd packaging/windows/
        $env:TAG_NAME -Match '\d+\.\d+\.\d+'
        .\create-setup.ps1 -AppName "Formula" -AppFolderName "Formula" -AppVer $Matches[0] -Vst3File64 "./Formula.vst3" -StandaloneFile64 "./Formula.exe" -OutputFileName formula-windows
        cd ../..
    
    - name: Upload to release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        file: 'packaging/windows/Output/formula-windows.exe'
        prerelease: ${{ inputs.release_candidate == 'true' }}
        tag_name: '${{ inputs.release_tag }}'