name: Build plugin (MacOS)
on: 
  workflow_call:
    inputs:
      release_tag:
        type: string
        required: true
      debug_enabled:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g. 2.1.0-rc.1)'     
        required: true
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false

jobs:  
  build:
    name: Building the project
    runs-on: macos-11
    steps: 
    - name: Git Checkout
      uses: actions/checkout@v2
        
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      
    - name: Configure
      run: |
        chmod +x configure-mac.sh
        ./configure-mac.sh
        
    - name: CMake x64
      run: |
        cmake -G Ninja . -DCMAKE_OSX_ARCHITECTURES="x86_64" -DCMAKE_TOOLCHAIN_FILE="./vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="x64-osx" -DCMAKE_BUILD_TYPE=Release
            
    - name: CMake Build x64
      run: |
        cmake --build . --target Formula_All
        mv Formula_artefacts Formula_artefacts_x64
        
    - name: CMake ARM64
      run: |
        rm -rf CMakeFiles CMakeCache.txt
        cmake -G Ninja . -DCMAKE_OSX_ARCHITECTURES="arm64" -DCMAKE_TOOLCHAIN_FILE="./vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="arm64-osx" -DCMAKE_BUILD_TYPE=Release
            
    - name: CMake Build ARM64
      run: |
        cmake --build . --target Formula_All
        mv Formula_artefacts Formula_artefacts_arm64
        
    - name: Create fat binaries
      run: |
        mkdir /tmp/AU
        cp -R Formula_artefacts_x64/Release/AU/Formula.component /tmp/AU
        lipo Formula_artefacts_x64/Release/AU/Formula.component/Contents/MacOS/Formula \
            Formula_artefacts_arm64/Release/AU/Formula.component/Contents/MacOS/Formula \
            -create -output /tmp/AU/Formula.component/Contents/MacOS/Formula
        
        mkdir /tmp/VST3
        cp -R Formula_artefacts_x64/Release/VST3/Formula.vst3 /tmp/VST3
        lipo Formula_artefacts_x64/Release/VST3/Formula.vst3/Contents/MacOS/Formula \
            Formula_artefacts_arm64/Release/VST3/Formula.vst3/Contents/MacOS/Formula \
            -create -output /tmp/VST3/Formula.vst3/Contents/MacOS/Formula
            
        mkdir /tmp/Standalone
        cp -R Formula_artefacts_x64/Release/Standalone/Formula.app /tmp/Standalone
        lipo Formula_artefacts_x64/Release/Standalone/Formula.app/Contents/MacOS/Formula \
            Formula_artefacts_arm64/Release/Standalone/Formula.app/Contents/MacOS/Formula \
            -create -output /tmp/Standalone/Formula.app/Contents/MacOS/Formula
      
    - name: Create setup
      run: |
        export IDENTIFIER=com.soundspear.pkg.formula
        export SYSTEM_PLUGINS_DIR=/Library/Audio/Plug-Ins
        
        pkgbuild --root "/tmp/VST3/" --identifier "$IDENTIFIER.vst3" --install-location "$SYSTEM_PLUGINS_DIR/VST3" Formula_VST3.pkg
        pkgbuild --root "/tmp/AU/" --identifier "$IDENTIFIER.component" --install-location "$SYSTEM_PLUGINS_DIR/Components" Formula_AU.pkg
        pkgbuild --root "/tmp/Standalone/" --identifier "$IDENTIFIER.app" --install-location "/Applications" Formula_Standalone_Application.pkg

        zip -r formula-macos.zip *.pkg        
        
    - name: Upload to release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        file: 'formula-macos.zip'
        prerelease: true
        tag_name: '${{ inputs.release_tag }}'